table colombianTolls
	lineageTag: a6cd3b0e-7e55-4556-a219-2fbff2a4cd6c

	column idpeaje
		dataType: string
		lineageTag: 83f68d7a-44e8-4ece-81aa-7b6b2797c8ea
		summarizeBy: none
		sourceColumn: idpeaje

		annotation SummarizationSetBy = Automatic

	column peaje
		dataType: string
		lineageTag: ee58ae72-fffe-40bb-8293-06a009d1f566
		summarizeBy: none
		sourceColumn: peaje

		annotation SummarizationSetBy = Automatic

	column categoriatarifa
		dataType: string
		lineageTag: 8fe178a4-274f-46b9-b560-4d275eb1d692
		summarizeBy: none
		sourceColumn: categoriatarifa

		annotation SummarizationSetBy = Automatic

	column desde
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 55279556-be70-4611-a422-726c1569bbe7
		summarizeBy: none
		sourceColumn: desde

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column valortarifa
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 2aa90ae8-e109-459c-857f-9a3fceabf923
		summarizeBy: sum
		sourceColumn: valortarifa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column cantidadtrafico
		dataType: int64
		formatString: 0
		lineageTag: c69d9c96-40ca-4280-b9be-890d975fe3f0
		summarizeBy: sum
		sourceColumn: cantidadtrafico

		annotation SummarizationSetBy = Automatic

	column cantidadevasores
		dataType: int64
		formatString: 0
		lineageTag: 325e9f89-1857-489a-9c0a-370f619573af
		summarizeBy: sum
		sourceColumn: cantidadevasores

		annotation SummarizationSetBy = Automatic

	column cantidadexentos787
		dataType: int64
		formatString: 0
		lineageTag: 7eb22629-2036-43ae-b714-e272156200fb
		summarizeBy: sum
		sourceColumn: cantidadexentos787

		annotation SummarizationSetBy = Automatic

	column anio
		dataType: int64
		formatString: 0
		lineageTag: c7866a63-4fb4-4594-ba22-838ec7bef0b2
		summarizeBy: sum
		sourceColumn: anio

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: string
		lineageTag: 6537e23f-23b9-49e9-b0f4-73b1e5dc7be4
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	partition colombianTolls = m
		mode: import
		source =
				let
				    Origen = R.Execute("
				        library(httr)
				        library(jsonlite)
				        library(dplyr)
				        library(lubridate)
				        library(stringr)
				
				        url <- 'https://www.datos.gov.co/resource/8yi9-t44c.json'
				
				        limit <- 1000
				        all_data <- list()
				
				        start_dates <- seq(
				            from = as.Date('2014-01-01'),
				            to   = Sys.Date(),
				            by   = 'month'
				        )
				
				        end_dates <- c(start_dates[-1] - 1, Sys.Date())
				
				        for (i in seq_along(start_dates)) {
				
				            offset <- 0
				
				            repeat {
				
				                where_clause <- paste0(
				                    ""desde >= '"",
				                    start_dates[i],
				                    ""' AND desde <= '"",
				                    end_dates[i],
				                    ""'""
				                )
				
				                res <- GET(
				                    url,
				                    query = list(
				                        '$limit'  = limit,
				                        '$offset' = offset,
				                        '$where'  = where_clause
				                    )
				                )
				
				                if (status_code(res) != 200) break
				
				                data <- fromJSON(
				                    content(res, 'text', encoding = 'UTF-8'),
				                    flatten = TRUE
				                )
				
				                if (length(data) == 0) break
				
				                all_data <- append(all_data, list(data))
				                offset <- offset + limit
				            }
				        }
				
				        df <- bind_rows(all_data)
				
				        if ('desde' %in% names(df)) {
				            df$desde <- as_date(df$desde)
				        }
				        if ('hasta' %in% names(df)) {
				            df$hasta <- as_date(df$hasta)
				        }
				
				        df <- df |>
				        mutate(
				            anio = as.integer(year(desde)),
				            mes = str_to_title(month(desde, label = TRUE, abbr = FALSE))
				        ) |>
				        select(-hasta)
				    "),
				
				    df1 = Origen{[Name = "df"]}[Value],
				    #"Tipo cambiado" = Table.TransformColumnTypes(df1,{{"valortarifa", Currency.Type}, {"cantidadtrafico", Int64.Type}, {"cantidadevasores", Int64.Type}, {"cantidadexentos787", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

