table toll_dictionary
	lineageTag: ab931d23-ab63-4c86-8bd0-03656a075583

	column peaje
		dataType: string
		lineageTag: 2f951db6-088b-4757-9a8d-ffa5977de436
		summarizeBy: none
		sourceColumn: peaje

		annotation SummarizationSetBy = Automatic

	column categoriatarifa
		dataType: string
		lineageTag: 496a83ba-b489-47c8-b3af-86398ea0943e
		summarizeBy: none
		sourceColumn: categoriatarifa

		annotation SummarizationSetBy = Automatic

	column valortarifa
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: aad86150-da35-46cb-8d9b-56b3ceffc81c
		summarizeBy: sum
		sourceColumn: valortarifa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: dadc638d-53e0-4827-a158-39473fb87fa1
		summarizeBy: none
		sourceColumn: month

		variation Variación
			isDefault
			relationship: 2f63601a-5bfc-4a9c-87eb-7c208e31ab93
			defaultHierarchy: LocalDateTable_aaab9a24-5d23-4fa4-93a3-d878ac7404b7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nombre del mes'
		dataType: string
		lineageTag: dec3b5d5-59c1-482c-a6b5-b7b93e638197
		summarizeBy: none
		sourceColumn: Nombre del mes

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 4e559ec8-9bc8-40b6-bec7-50c99fbe19e7
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	partition toll_dictionary = m
		mode: import
		source =
				let
					Source = colombianTolls,
					AddMonth = Table.AddColumn(Source, "month", each Date.ToText([desde], "dd/MM/yyyy")),
					SelectCols = Table.SelectColumns(AddMonth, {"peaje", "categoriatarifa", "valortarifa", "month"}),
					DistinctRows = Table.Distinct(SelectCols),
				    #"Tipo cambiado" = Table.TransformColumnTypes(DistinctRows,{{"month", type date}}),
				    #"Nombre del mes insertado" = Table.AddColumn(#"Tipo cambiado", "Nombre del mes", each Date.MonthName([month]), type text),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Nombre del mes insertado",{{"Nombre del mes", Text.Proper, type text}}),
				    #"Año insertado" = Table.AddColumn(#"Poner En Mayúsculas Cada Palabra", "Año", each Date.Year([month]), Int64.Type)
				in
					#"Año insertado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

