table 'Olympic Overview'
	lineageTag: f9436941-2190-4a3c-98ee-2c8834c4f39f

	column Date
		dataType: string
		lineageTag: 0844b9ac-b65e-4ac9-ab30-aead9e453491
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Host Country'
		dataType: string
		lineageTag: 88cfd54b-7677-4c10-aa8a-bf4781dd2f06
		summarizeBy: none
		sourceColumn: Host Country

		annotation SummarizationSetBy = Automatic

	column Athletes
		dataType: int64
		formatString: #,0
		lineageTag: d8ae64ef-2de4-4fc6-8484-f7950516a936
		summarizeBy: sum
		sourceColumn: Athletes

		annotation SummarizationSetBy = Automatic

	column Teams
		dataType: int64
		formatString: #,0
		lineageTag: 4bf16c87-24f8-426c-be66-08e80c02a0ef
		summarizeBy: sum
		sourceColumn: Teams

		annotation SummarizationSetBy = Automatic

	column Events
		dataType: int64
		formatString: #,0
		lineageTag: 75a3f5a7-8f21-4fbd-9aee-7283dfb6f5e3
		summarizeBy: sum
		sourceColumn: Events

		annotation SummarizationSetBy = Automatic

	column 'Olympic Session'
		dataType: string
		lineageTag: edba9582-2e2b-4fdb-905c-c43316d4a5c4
		summarizeBy: none
		sourceColumn: Olympic Session

		annotation SummarizationSetBy = Automatic

	column 'Olympic Logo URL'
		dataType: string
		lineageTag: 66b6c79d-1ab4-439b-8d23-761fdcfff56a
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Olympic Logo URL

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: 371a62ba-9ee6-45f0-90c7-8aaaed73c95c
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a7de0286-9171-4a26-bd81-032272b87890
		summarizeBy: sum
		sourceColumn: Índice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: bd515de2-24a4-45f1-8132-2969ae8ae9ff
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Host City - Year'
		dataType: string
		isHidden
		lineageTag: f684084c-0332-4fd4-8080-725c88be17f2
		summarizeBy: none
		sourceColumn: Host City - Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		isHidden
		lineageTag: 73c0cd4a-6690-4fd7-928e-e015c8864475
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 2e24f3ae-3e5f-4af6-9d3f-0a15bb68efc2
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	partition 'Olympic Overview' = m
		mode: import
		source =
				let
				    // Loaded Olympic host statistics from the project CSV.
				    Source = Csv.Document(File.Contents("C:\Users\NICOL\OneDrive\28 octubre\HV\ProcesosSelección\Extra\PowerBI-projects\Olympic\data\Olympic Overview.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    // Used the first CSV row as the column headers.
				    #"Promoted Column Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    // Set text and whole-number types for the source fields.
				    #"Typed Olympic Overview Fields" = Table.TransformColumnTypes(#"Promoted Column Headers",{{"Date", type text}, {"Country", type text}, {"Athletes", Int64.Type}, {"Teams", Int64.Type}, {"Events", Int64.Type}, {"Event Name", type text}, {"Olympic Logo URL", type text}}),
				    // Derived each event's season from its name.
				    #"Added Olympic Season" = Table.AddColumn(#"Typed Olympic Overview Fields", "Season", each if Text.Contains([Event Name], "Winter") then "Winter" else "Summer"),
				    // Extracted the host city and year portion of the event name.
				    #"Added Host City and Year" = Table.AddColumn(#"Added Olympic Season", "Host City - Year", each Text.AfterDelimiter([Event Name], "Games "), type text),
				    // Set the season field to text before trimming its values.
				    #"Typed Olympic Season" = Table.TransformColumnTypes(#"Added Host City and Year",{{"Season", type text}}),
				    // Removed leading and trailing whitespace from season labels.
				    #"Trimmed Olympic Season Labels" = Table.TransformColumns(#"Typed Olympic Season", {{"Season", each Text.Trim(_)}}),
				    // Added a sequential row index for downstream report usage.
				    #"Added Olympic Row Index" = Table.AddIndexColumn(#"Trimmed Olympic Season Labels", "Índice", 1, 1, Int64.Type),
				    // Extracted each host city from the city-year label.
				    #"Extracted Host City" = Table.AddColumn(#"Added Olympic Row Index", "Host City", each Text.BeforeDelimiter([#"Host City - Year"], " ", {0, RelativePosition.FromEnd}), type text),
				    // Expanded the United States country name for consistent matching.
				    #"Standardized United States Country Name" = Table.ReplaceValue(#"Extracted Host City","United States","United States of America",Replacer.ReplaceText,{"Country"}),
				    // Expanded China's country name for consistent matching.
				    #"Standardized China Country Name" = Table.ReplaceValue(#"Standardized United States Country Name","China","People's Republic of China",Replacer.ReplaceText,{"Country"}),
				    // Resolved a combined country value to its host country.
				    #"Corrected Australia Host Country" = Table.ReplaceValue(#"Standardized China Country Name","Australia, Sweden","Australia",Replacer.ReplaceText,{"Country"}),
				    // Extracted the event year from the final word of the event name.
				    #"Extracted Olympic Year" = Table.AddColumn(#"Corrected Australia Host Country", "Year", each Text.AfterDelimiter([Event Name], " ", {0, RelativePosition.FromEnd}), type text),
				    // Removed periods so city-year values match the history lookup.
				    #"Removed Host City Year Periods" = Table.ReplaceValue(#"Extracted Olympic Year",".","",Replacer.ReplaceText,{"Host City - Year"}),
				    // Matched host city-year values to historical event URLs.
				    #"Joined Historical Event URLs" = Table.NestedJoin(#"Removed Host City Year Periods", {"Host City - Year"}, past_olympics, {"City"}, "past_olympics", JoinKind.LeftOuter),
				    // Expanded any matching historical URL for each Olympic event.
				    #"Expanded Historical Event URLs" = Table.ExpandTableColumn(#"Joined Historical Event URLs", "past_olympics", {"URL"}, {"URL"}),
				    // Standardized the St. abbreviation in host city-year values.
				    #"Standardized Host City Abbreviation" = Table.ReplaceValue(#"Expanded Historical Event URLs","St ","St. ",Replacer.ReplaceText,{"Host City - Year"}),
				    // Matched host countries to their National Olympic Committee codes.
				    #"Joined Olympic Country Codes" = Table.NestedJoin(#"Standardized Host City Abbreviation", {"Country"}, #"Olympic Countrires", {"Country Name"}, "Olympic Countrires", JoinKind.LeftOuter),
				    // Expanded any matching NOC code for each host event.
				    #"Expanded Olympic Country Codes" = Table.ExpandTableColumn(#"Joined Olympic Country Codes", "Olympic Countrires", {"NOC"}, {"NOC"}),
				    // Combined each NOC code and host city into a location label.
				    #"Combined Olympic Location" = Table.CombineColumns(#"Expanded Olympic Country Codes",{"NOC", "Host City"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Location"),
				    // Renamed source fields to their semantic-model names.
				    #"Renamed Olympic Overview Fields" = Table.RenameColumns(#"Combined Olympic Location",{{"Country", "Host Country"}, {"Event Name", "Olympic Session"}}),
				    // Standardized punctuation in the Milano-Cortina session name.
				    #"Standardized Milano Cortina Session" = Table.ReplaceValue(#"Renamed Olympic Overview Fields","Olympic Winter Games Milano-Cortina 2026","Olympic Winter Games Milano Cortina 2026",Replacer.ReplaceText,{"Olympic Session"}),
				    // Standardized punctuation in the Milano-Cortina host city label.
				    #"Standardized Milano Cortina Host City" = Table.ReplaceValue(#"Standardized Milano Cortina Session","Milano-Cortina 2026","Milano Cortina 2026",Replacer.ReplaceText,{"Host City - Year"})
				in
				    #"Standardized Milano Cortina Host City"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table
