table 'Olympic Countrires'
	lineageTag: 5e7cf5d7-c362-4a7b-9817-626b008e9334

	/// National Olympic Committee
	column NOC
		dataType: string
		lineageTag: 257b85fc-7df4-445c-b742-39cf7d282124
		summarizeBy: none
		sourceColumn: NOC

		annotation SummarizationSetBy = Automatic

	column 'Country Name'
		dataType: string
		lineageTag: 40b44102-a2b1-4a6d-b9be-21c8c2347533
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	partition 'Olympic Countrires' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\NICOL\OneDrive\28 octubre\HV\ProcesosSelección\Extra\Olympic\Olympic Countrires.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Column1", type text}, {"Column2", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Country Code", type text}, {"Country Name", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado1",{{"Country Code", "NOC"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

