table 'Olympic Countrires'
	lineageTag: 5e7cf5d7-c362-4a7b-9817-626b008e9334

	/// National Olympic Committee
	column NOC
		dataType: string
		lineageTag: 257b85fc-7df4-445c-b742-39cf7d282124
		summarizeBy: none
		sourceColumn: NOC

		annotation SummarizationSetBy = Automatic

	column 'Country Name'
		dataType: string
		lineageTag: 40b44102-a2b1-4a6d-b9be-21c8c2347533
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	partition 'Olympic Countrires' = m
		mode: import
		source =
				let
				    // Loaded the country lookup data from the project CSV.
				    Source = Csv.Document(File.Contents("C:\Users\NICOL\OneDrive\28 octubre\HV\ProcesosSelección\Extra\PowerBI-projects\Olympic\data\Olympic Countrires.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    // Set text types before promoting the source headers.
				    #"Assigned Initial Column Types" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    // Used the first CSV row as the column headers.
				    #"Promoted Column Headers" = Table.PromoteHeaders(#"Assigned Initial Column Types", [PromoteAllScalars=true]),
				    // Set the data types for the country lookup fields.
				    #"Typed Country Fields" = Table.TransformColumnTypes(#"Promoted Column Headers",{{"Country Code", type text}, {"Country Name", type text}}),
				    // Renamed the country code to the model's NOC field name.
				    #"Renamed Country Code to NOC" = Table.RenameColumns(#"Typed Country Fields",{{"Country Code", "NOC"}})
				in
				    #"Renamed Country Code to NOC"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table
